### ISSUE TITLE
Crude divergence metrics

### ISSUE THREAD

**Issue by adammwilson** [AdamWilsonLab/emma_report#16]
Develop 1-3 easy divergence metrics to add to park report pages:

This could include: last NDVI observation minus 1) long term mean NDVI and 2) last 3 months NDVI to get a crude idea of how things are changing.

**Comment by bmaitner** [comment]
1 has been implemented, working on 2.

**Comment by bmaitner** [comment]
2 has been implemented and is available in the current reports.  I compare the current NDVI with the mean NDVI over the last 90 days (excluding the most recent layer).
